# -*- coding: utf-8 -*-
# EspaTV — Copyright (C) 2024-2026 RubénSDFA1labernt (github.com/espakodi)
# Licencia: GPL-2.0-or-later — Consulta el archivo LICENSE para mas detalles.
# Datos de contenido YouTube para la seccion Catalogo de EspaTV.
# Todas las listas de videos, canales y playlists de YouTube van aqui.

FELICIDAD_VERANIEGA_YT = {
    "Grand Prix": [
        {"name": "El Grand Prix del Verano (Oficial)", "type": "browser", "url": "https://www.youtube.com/@elgrandprixdelveranooficia2289", "desc": "Canal oficial del Grand Prix."},
        {"name": "El Grand Prix - Temporadas", "type": "channel", "yt_id": "UC0ztGaCMJ_zhuSGlDJaR6Vg", "desc": "Canal con temporadas del Grand Prix."},
        {"name": "Grand Prix - Canal Momentazos", "type": "channel", "yt_id": "UCLuXcaJaGCpM-ShNWLm1nOA", "desc": "Momentos memorables del Grand Prix."},
        {"name": "Playlist: Grand Prix Completo", "type": "playlist", "yt_id": "PLJSMlEehU05l5YkYoGVJdn6bSUlhVTYo9", "desc": "Episodios completos del Grand Prix."},
        {"name": "Playlist: Grand Prix Clasico", "type": "playlist", "yt_id": "PLc6y_bIejLFGLonpdNAsbL4ZDUE6GFBPR", "desc": "Capitulos clasicos del Grand Prix."},
        {"name": "Playlist: Grand Prix Recopilacion 1", "type": "playlist", "yt_id": "PLYxQSwFxhkl-wU7O1Ns-iuNGDs8LSUSPY", "desc": "Recopilacion de momentos del Grand Prix."},
        {"name": "Playlist: Grand Prix Recopilacion 2", "type": "playlist", "yt_id": "PLYxQSwFxhkl_3z924ADB8O5FIXBzlLRWm", "desc": "Mas recopilaciones del Grand Prix."},
        {"name": "Playlist: Grand Prix Recopilacion 3", "type": "playlist", "yt_id": "PLYxQSwFxhkl906hNtRawlL_5YC6WVKmbk", "desc": "Tercera recopilacion del Grand Prix."},
        {"name": "Playlist: Grand Prix Momentos", "type": "playlist", "yt_id": "PL5kC8ClLC6d6gJIIfMC2oZRPyy7Y46Zyi", "desc": "Los mejores momentos del Grand Prix."},
        {"name": "Playlist: Grand Prix Mix", "type": "playlist", "yt_id": "PLwAXiRCBg3hL0PGFc5IULbxzvwzsgAh9h", "desc": "Mix de videos del Grand Prix."},
        {"name": "Grand Prix - Mejores pruebas", "type": "video", "yt_id": "Z8H30Sl-OyU", "desc": "Recopilacion de las mejores pruebas."},
        {"name": "Grand Prix - Caidas epicas", "type": "video", "yt_id": "4X1X4p2emq8", "desc": "Las caidas mas epicas del Grand Prix."},
        {"name": "Grand Prix - Momentazos", "type": "video", "yt_id": "8YXNUf1TjZk", "desc": "Momentazos inolvidables."},
        {"name": "Grand Prix - Compilacion", "type": "video", "yt_id": "SDvURjTdQns", "desc": "Compilacion de escenas del Grand Prix."},
        {"name": "Grand Prix - Clasico", "type": "video", "yt_id": "Pf49fohrKhg", "desc": "Video clasico del Grand Prix."},
        {"name": "#ElGrandPrix en YouTube", "type": "browser", "url": "https://www.youtube.com/hashtag/elgrandprix", "desc": "Busqueda por hashtag en YouTube (solo navegador)."},
        {"name": "Grand Prix 1996 | Programa 2", "type": "video", "yt_id": "Hs8ad1_YRPY", "desc": "Programa completo."},
        {"name": "Grand Prix 1996 | Programa 11", "type": "video", "yt_id": "ZuwGhheudkY", "desc": "Programa completo."},
        {"name": "Grand Prix 1996 | Gran Final", "type": "video", "yt_id": "VzsNTpF-iVQ", "desc": "Gran Final completa."},
        {"name": "Grand Prix 1996 | Lo Mejor (Especial)", "type": "video", "yt_id": "45OEaeU3tqg", "desc": "Especial con lo mejor de 1996."},
        {"name": "Grand Prix 1997 | Programa 1", "type": "video", "yt_id": "4YiNmoNgQ4I", "desc": "Programa completo."},
        {"name": "Grand Prix 1997 | Programa 2", "type": "video", "yt_id": "WfjmE5vfen0", "desc": "Programa completo."},
        {"name": "Grand Prix 1997 | Programa 4", "type": "video", "yt_id": "7NM3P_eetGs", "desc": "Programa completo."},
        {"name": "Grand Prix 1997 | Programa 5", "type": "video", "yt_id": "MhnIhPtmA98", "desc": "Programa completo."},
        {"name": "Grand Prix 1997 | Programa 11", "type": "video", "yt_id": "sKR9oYTQWUw", "desc": "Programa completo."},
        {"name": "Grand Prix 1997 | Gran Final", "type": "video", "yt_id": "mS289pnZ-oQ", "desc": "Gran Final completa."},
        {"name": "Grand Prix 1997 | Lo Mejor (Especial)", "type": "video", "yt_id": "XgAUc5WxQX8", "desc": "Especial con lo mejor de 1997."},
        {"name": "Grand Prix 1998 | Programa 4", "type": "video", "yt_id": "GyYJN_yPzvY", "desc": "Programa completo."},
        {"name": "Grand Prix 1999 | Programa 1", "type": "video", "yt_id": "zo34KGgHE_o", "desc": "Programa completo."},
        {"name": "Grand Prix 2000 | Programa 4", "type": "video", "yt_id": "CdISboCpeUw", "desc": "Programa completo."},
        {"name": "Grand Prix 2000", "type": "video", "yt_id": "nSDkuuPhLsk", "desc": "Episodio del Grand Prix 2000."},
        {"name": "Grand Prix 2001 | Programa 8", "type": "video", "yt_id": "cXmpUbs6a0k", "desc": "Programa completo."},
        {"name": "Grand Prix 2002 | Programa 7", "type": "video", "yt_id": "xybxp_nGMMA", "desc": "Programa completo."},
        {"name": "Grand Prix 2003 | Gran Final", "type": "video", "yt_id": "RQo69she2RA", "desc": "Gran Final completa."},
        {"name": "Grand Prix 2004 | Gran Final", "type": "video", "yt_id": "HICof_zg56w", "desc": "Gran Final completa."},
        {"name": "Grand Prix 2004 | La vaca pichichi con 2 vaquillas", "type": "video", "yt_id": "rHv-hztgSJc", "desc": "Momento memorable del Grand Prix 2004."},
        {"name": "Grand Prix 2005 | Programa 1", "type": "video", "yt_id": "IZ0yeBqHLho", "desc": "Programa completo."},
        {"name": "Grand Prix 2005 | Programa 11", "type": "video", "yt_id": "JKuycKG_ZEY", "desc": "Programa completo."},
        {"name": "Grand Prix 2005 | Gran Final", "type": "video", "yt_id": "p6k5owuLsnU", "desc": "Gran Final completa."},
        {"name": "Grand Prix 2005 | Lo Mejor (Especial)", "type": "video", "yt_id": "5JAGoNMOGts", "desc": "Especial con lo mejor de 2005."},
        {"name": "Grand Prix 2008 | Programa 1", "type": "video", "yt_id": "ISDrKh2B6Bw", "desc": "Programa completo."},
    ],
    "Humor Amarillo": [
        {"name": "Humor Amarillo - Episodio 1", "type": "video", "yt_id": "SUMHWt7h6Wc", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 2", "type": "video", "yt_id": "UlmL8Bb-VE4", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 3", "type": "video", "yt_id": "dW0dCNXDRLQ", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 4", "type": "video", "yt_id": "iWpRlDCuW-I", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 5", "type": "video", "yt_id": "Ais3NpftfFY", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 6", "type": "video", "yt_id": "F4gq-1Lc4pY", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 7", "type": "video", "yt_id": "5k22FPHBlJw", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 8", "type": "video", "yt_id": "aY6rJ3aqxm8", "desc": "Episodio de Humor Amarillo."},
        {"name": "Playlist: Humor Amarillo Completo 1", "type": "playlist", "yt_id": "PLUMbDZEzn26ICmJddfvN7D8BsmTJIHy3K", "desc": "Playlist con episodios de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 9", "type": "video", "yt_id": "2E6Cgren8-M", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 10", "type": "video", "yt_id": "4Ubwt_fHb8o", "desc": "Episodio de Humor Amarillo."},
        {"name": "Playlist: Humor Amarillo Completo 2", "type": "playlist", "yt_id": "PLbBEI8QS_lSBJnwdscItR71fiD5DvDHBF", "desc": "Otra playlist con episodios de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 11", "type": "video", "yt_id": "HiGhJ8v_ECw", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 12", "type": "video", "yt_id": "IESJExVJHZA", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 13", "type": "video", "yt_id": "cfRNH3X_ssg", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 14", "type": "video", "yt_id": "zdEZPAU0oiI", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 15", "type": "video", "yt_id": "Duft3i_jLrU", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 16", "type": "video", "yt_id": "EgAcOWc4TL4", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 17", "type": "video", "yt_id": "DLg5kyOmuVI", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 18", "type": "video", "yt_id": "CmuZXZm69q0", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 19", "type": "video", "yt_id": "vk9UwALeacI", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 20", "type": "video", "yt_id": "X476k8uqjJc", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 21", "type": "video", "yt_id": "42FhIHUwt2c", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 22", "type": "video", "yt_id": "uuaA15ZU3RQ", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 23", "type": "video", "yt_id": "JU8FKYL4hWg", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 24", "type": "video", "yt_id": "vySiI7wXfZY", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 25", "type": "video", "yt_id": "sYm3o3oG39U", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 26", "type": "video", "yt_id": "-ZryAjj5OIY", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 27", "type": "video", "yt_id": "tv4OImZ6tZI", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 28", "type": "video", "yt_id": "itL_bnD3LNQ", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 29", "type": "video", "yt_id": "lc5KpMpd4Wk", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 30", "type": "video", "yt_id": "ihSYsy10ZA4", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 31", "type": "video", "yt_id": "RIKGtSTbsIk", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 32", "type": "video", "yt_id": "c1FbndzdjQ8", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 33", "type": "video", "yt_id": "ixmn_EisFIY", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 34", "type": "video", "yt_id": "SA9JsuJvs9A", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 35", "type": "video", "yt_id": "FzVutHnaD58", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 36", "type": "video", "yt_id": "8XDcRGe9_Ts", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 37", "type": "video", "yt_id": "kCElR3aIqZM", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 38", "type": "video", "yt_id": "Y5gydgGqLtU", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 39", "type": "video", "yt_id": "KAnT5Wfze7c", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 40", "type": "video", "yt_id": "aE5XcVEPpu4", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 41", "type": "video", "yt_id": "aejD5-2Rs5w", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 42", "type": "video", "yt_id": "yBQPw3E3xIM", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 43", "type": "video", "yt_id": "DNoV8obMKn4", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 44", "type": "video", "yt_id": "p6PxJ7I2Io4", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 45", "type": "video", "yt_id": "r1A_lhZMe0w", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 46", "type": "video", "yt_id": "f-f_IjNaUUU", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 47", "type": "video", "yt_id": "-Ef04WITqbg", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 48", "type": "video", "yt_id": "5b6hSPwe8n8", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 49", "type": "video", "yt_id": "ME_F4ErrIV0", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 50", "type": "video", "yt_id": "522_6iflGHA", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 51", "type": "video", "yt_id": "FNCogL0ucYU", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 52", "type": "video", "yt_id": "wliSQKFU7uk", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 53", "type": "video", "yt_id": "OhxbT3pQxSw", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 54", "type": "video", "yt_id": "dB_deyOM5aI", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 55", "type": "video", "yt_id": "M8_9OfjY1Nw", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 56", "type": "video", "yt_id": "9EZXc3MfgGU", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 57", "type": "video", "yt_id": "IPCXP4bngjU", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 58", "type": "video", "yt_id": "JbhpC89F7CI", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 59", "type": "video", "yt_id": "k8v0HO-Sw8M", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 60", "type": "video", "yt_id": "UBotUXajUu4", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 61", "type": "video", "yt_id": "RtUs_xWYM2M", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 62", "type": "video", "yt_id": "-qU2QFV3LbE", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 63", "type": "video", "yt_id": "d8itZJcOtlk", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 64", "type": "video", "yt_id": "htTQLSSMbks", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 65", "type": "video", "yt_id": "xoWxkzHPBmY", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 66", "type": "video", "yt_id": "EwHWSuS1Rrc", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 67", "type": "video", "yt_id": "bakvq4Lw8XM", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 68", "type": "video", "yt_id": "RlQ4O75J45E", "desc": "Episodio de Humor Amarillo."},
        {"name": "Playlist: Humor Amarillo Completo 3", "type": "playlist", "yt_id": "PLUMbDZEzn26I5Ki_DuqVRx-eJskLsRC3k", "desc": "Playlist con episodios de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 69", "type": "video", "yt_id": "gkItT3WdWlg", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 70", "type": "video", "yt_id": "FztfN1PSPHQ", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 71", "type": "video", "yt_id": "5_IlHiruasI", "desc": "Episodio de Humor Amarillo."},
        {"name": "Playlist: Humor Amarillo Completo 4", "type": "playlist", "yt_id": "PLt7BqXSc0Fjfvktd0dBu1cWu0NrUuvTBo", "desc": "Playlist con episodios de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 72", "type": "video", "yt_id": "UaeBLyRvDsQ", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 73", "type": "video", "yt_id": "ILRxYULYHqY", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 74", "type": "video", "yt_id": "TdV3FkRo9to", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 75", "type": "video", "yt_id": "jzjBDOshBYU", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 76", "type": "video", "yt_id": "gaJt8KhqpyQ", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 77", "type": "video", "yt_id": "Mb9xNQ2uUrs", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 78", "type": "video", "yt_id": "oSw5xNBehfM", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 79", "type": "video", "yt_id": "ETwT4_ULxTA", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 80", "type": "video", "yt_id": "xOSR6RtB3og", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 81", "type": "video", "yt_id": "-1vgWSMx2lY", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 82", "type": "video", "yt_id": "viB-Lb-ITj8", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 83", "type": "video", "yt_id": "xYZxrka7iS8", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 84", "type": "video", "yt_id": "AmFFrhS0qL4", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 85", "type": "video", "yt_id": "ab2PJSYYRWM", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 86", "type": "video", "yt_id": "1PZl1smSG6s", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 87", "type": "video", "yt_id": "AJOxuHeCAjs", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 88", "type": "video", "yt_id": "XNtNSVPkxqU", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 89", "type": "video", "yt_id": "uryUIqGDNxY", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 90", "type": "video", "yt_id": "zaMQtdOXcmw", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 91", "type": "video", "yt_id": "VYJhvoyEn3w", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 92", "type": "video", "yt_id": "Lv5VwTKR69U", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 93", "type": "video", "yt_id": "jkRijVVoONY", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 94", "type": "video", "yt_id": "HppfxgcdHW0", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 95", "type": "video", "yt_id": "wHoJcHJXiww", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 96", "type": "video", "yt_id": "m16HYFH-1jk", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 97", "type": "video", "yt_id": "iHdzR4fCu6o", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 98", "type": "video", "yt_id": "3qyvgUAXAz8", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 99", "type": "video", "yt_id": "IWSvRKgX5Ro", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 100", "type": "video", "yt_id": "PguUdXaId8M", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 101", "type": "video", "yt_id": "wxYVw5mOECc", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 102", "type": "video", "yt_id": "xpHfZwvtX5s", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 103", "type": "video", "yt_id": "KwwDsrwnqTQ", "desc": "Episodio de Humor Amarillo."},
        {"name": "Humor Amarillo - Episodio 104", "type": "video", "yt_id": "4dtgg654Tds", "desc": "Episodio de Humor Amarillo."},
    ],
    "Summer Mix / Musica Verano": [
        {"name": "The Good Life Radio", "yt_id": "UChs0pSaEoNLV4mevBFGaoKA", "desc": "Summer vibes, feel-good music 24/7."},
        {"name": "Ibiza Summer Mix 2024 - Tropical Deep House Chill Out", "type": "video", "yt_id": "uD8ZjrHxP3Q", "desc": "Best of tropical deep house chillout lounge.\n217.3M visitas"},
        {"name": "Summer mix - DJ Snake, Avicii, Justin Bieber, Rihanna, Kygo", "type": "video", "yt_id": "JL-YFJTxftU", "desc": "Sweet summer vibes on the beach.\n116.8M visitas"},
        {"name": "Calvin Harris - Summer (Official Video)", "type": "video", "yt_id": "ebXbLfLACGM", "desc": "El clasico del verano de Calvin Harris.\n1.8B visitas"},
        {"name": "Mega Hits 2025 - Best Of Vocal Deep House Summer Mix", "type": "video", "yt_id": "N6DW31S_oyI", "desc": "Lo mejor del deep house vocal.\n109.2M visitas"},
        {"name": "Avicii, Dua Lipa, Coldplay, Martin Garrix - Summer Vibes #2", "type": "video", "yt_id": "xfgBijPAR6s", "desc": "Summer vibes con los mejores DJs.\n106.5M visitas"},
        {"name": "Eurythmics - Sweet Dreams (Ibiza Deep Summer Remix)", "type": "video", "yt_id": "p9j8RGTqju0", "desc": "Sweet Dreams remezclado para Ibiza.\n106.1M visitas"},
        {"name": "Feeling Happy - Stay See Summer Mix 2015", "type": "video", "yt_id": "UPftsIwGNoQ", "desc": "Melodic deep house y vocal house.\n104.9M visitas"},
        {"name": "EHRLING - Nu Lounge Bar Music 2017 (Mix #1)", "type": "video", "yt_id": "jpv2tMJJuz0", "desc": "Chill beats para lounge bar.\n101.0M visitas"},
        {"name": "Summer nostalgia - Rihanna, Avicii, Justin Bieber, Kygo", "type": "video", "yt_id": "JFFq8xgBQZI", "desc": "Mix de nostalgia veraniega.\n70.1M visitas"},
        {"name": "Best Music Mix 2017 - Shuffle Music Video HD", "type": "video", "yt_id": "D7ztZ_qhx5Q", "desc": "Melbourne Bounce music mix.\n68.3M visitas"},
        {"name": "Summer Mix 2023 - Chillout Lounge Relaxing Deep House", "type": "video", "yt_id": "8kVI621fZug", "desc": "Chillout lounge relajante.\n63.1M visitas"},
        {"name": "Summer Mix - Une Belle Journee D'ete - Melodic Deep House", "type": "video", "yt_id": "mMgHsufmjEA", "desc": "Un hermoso dia de verano en deep house.\n55.6M visitas"},
        {"name": "Deep House Mix 2020 Vol.1 - Mixed By TSG", "type": "video", "yt_id": "cnVPm1dGQJc", "desc": "Deep house mix session.\n50.0M visitas"},
        {"name": "Mega Hits 2021 - Best Of Vocal Deep House Summer Mix #9", "type": "video", "yt_id": "or047P2NOjc", "desc": "Lo mejor del vocal deep house 2021.\n49.7M visitas"},
        {"name": "Musica Summer Alegre para Trabajar", "type": "video", "yt_id": "KgdDQGSL0qs", "desc": "Musica alegre para oficinas y tiendas.\n41.1M visitas"},
        {"name": "Alan Walker, Dua Lipa, Coldplay - Summer Vibes #1", "type": "video", "yt_id": "dIQq3AZkQqg", "desc": "Summer vibes con Alan Walker y mas.\n39.4M visitas"},
        {"name": "Summer Music Mix 2023 - Best Of Vocals Deep House", "type": "video", "yt_id": "rSc_K7KjEGo", "desc": "Alan Walker, Coldplay, Selena Gomez style.\n33.9M visitas"},
        {"name": "2010s roadtrip mix - nostalgia playlist", "type": "video", "yt_id": "0kXdYDeOc4U", "desc": "POV: roadtrip en una noche de verano de 2010.\n27.2M visitas"},
        {"name": "Summer songs to dance - Best songs that make you dance", "type": "video", "yt_id": "hOyn0bCydZo", "desc": "Canciones de verano para bailar.\n26.5M visitas"},
        {"name": "DJ NYK - Bollywood Sunset Mix (Italy) Cinque Terre", "type": "video", "yt_id": "vMpaSBYh5pA", "desc": "Sunset set desde Vernazza, Cinque Terre.\n25.2M visitas"},
        {"name": "TSYN x Musique Chic Summer Tape - By Klingande", "type": "video", "yt_id": "ismvoxh7NPU", "desc": "Summer mix por Klingande.\n24.6M visitas"},
        {"name": "AFRO HOUSE MIX 2025 - Adam Port, Hugel, Keinemusik", "type": "video", "yt_id": "Y3POl9bm4g4", "desc": "Live DJ set de afro house.\n24.2M visitas"},
        {"name": "Songs That Bring You Back To Summer #1 - Kygo, Robin Schulz", "type": "video", "yt_id": "Zu6QKV7HPmA", "desc": "Canciones que te devuelven al verano.\n20.4M visitas"},
        {"name": "David Bisbal - Amor Ame (Summer Mix)", "type": "video", "yt_id": "Zpg5fhCGhOQ", "desc": "David Bisbal en version summer mix.\n20.1M visitas"},
        {"name": "Summer Chill Mix - Tropical and Deep House", "type": "video", "yt_id": "-fjmSE9Ez6w", "desc": "Tropical y deep house chill.\n17.7M visitas"},
        {"name": "Summer 2017 mix - nostalgia playlist", "type": "video", "yt_id": "tqUUNMq71vk", "desc": "POV: roadtrip en verano de 2017.\n15.9M visitas"},
        {"name": "All Genres Party Music Mix 2026 - Wedding DJ Set", "type": "video", "yt_id": "Pn3pI4EsmWE", "desc": "Mix de todos los generos para fiesta.\n13.7M visitas"},
        {"name": "Afro House Sunset Mix - Punta del Este", "type": "video", "yt_id": "mm8PugX6QZ0", "desc": "Afro house sunset desde Punta del Este.\n13.4M visitas"},
        {"name": "Summer Mix 2021 - Best Of Deep House Sessions", "type": "video", "yt_id": "BnCK27j7gnM", "desc": "Deep house sessions by Magic.\n13.1M visitas"},
        {"name": "Good Vibes - Chill House Music", "type": "video", "yt_id": "U-vO38hfbT4", "desc": "Musica chill house para buenas vibras.\n12.9M visitas"},
        {"name": "Club Classics (August 2020) - Ministry Of Sound", "type": "video", "yt_id": "tXDk2C_IO2o", "desc": "Clasicos de club por Ministry Of Sound.\n12.1M visitas"},
        {"name": "SUMMER AFRO HOUSE Sunset Mix - Adam Port, Avicii, Coldplay", "type": "video", "yt_id": "PAoUgUHpt30", "desc": "Summer vibes afro house sunset.\n11.8M visitas"},
        {"name": "Chill Summer Lofi - lo-fi hip hop beats", "type": "video", "yt_id": "kyqpSycLASY", "desc": "Beats lofi instrumentales para el verano.\n11.7M visitas"},
        {"name": "Rihanna, Ed Sheeran, Alan Walker - Summer Nostalgia #1", "type": "video", "yt_id": "xBblttAMNTI", "desc": "Summer nostalgia con los mejores artistas.\n11.6M visitas"},
    ],
    "Agua: Parques Acuáticos": [
        {"name": "Aqualandia Benidorm - Todos los toboganes 2025", "type": "video", "yt_id": "88-q11yr4Zs", "desc": "Todos los toboganes de Aqualandia Benidorm POV."},
        {"name": "Aquatropic Almuñecar 2025 - Todos los toboganes", "type": "video", "yt_id": "s5qIHBDb0tE", "desc": "Novedades y toboganes de Aquatropic Granada."},
        {"name": "Aquopolis Costa Dorada 2025 - Todos los toboganes", "type": "video", "yt_id": "nYNH0n5FeNE", "desc": "Atracciones de Aquopolis en La Pineda."},
        {"name": "Los 5 parques acuáticos más INCREÍBLES de España (2026)", "type": "video", "yt_id": "R0CURDNqong", "desc": "Ranking de los mejores parques de España."},
        {"name": "Tobogán Extremo De Tenerife (MikelTube)", "type": "video", "yt_id": "O7oqfv0qm9s", "desc": "MikelTube prueba el tobogan de Siam Park."},
        {"name": "Aquapark Cerceda 2025 - Galicia", "type": "video", "yt_id": "bUvdOO4o82s", "desc": "Novedades y toboganes en Aquapark Cerceda."},
        {"name": "Parque Warner Beach - Madrid", "type": "video", "yt_id": "NlGR3MdZxU0", "desc": "Recorrido en 4K por Parque Warner Beach."},
        {"name": "Western Water Park Mallorca - Todos los toboganes", "type": "video", "yt_id": "0AlC4u-gycA", "desc": "POV de todas las atracciones acuaticas de Mallorca."},
        {"name": "Aquavelis Torre del Mar 2025 - Málaga", "type": "video", "yt_id": "ERQqBSDZFXM", "desc": "Toboganes en la Costa del Sol."},
        {"name": "Aquopolis Cullera - Nueva Atracción", "type": "video", "yt_id": "l-Me0YO40DI", "desc": "Novedades en el parque acuatico de Valencia."},
        {"name": "Aquarama Benicàssim 2025 - Castellón", "type": "video", "yt_id": "-oc-DZJi7n4", "desc": "Todos los toboganes y novedades en Aquarama."},
        {"name": "Aquasierra 2025 - Parque Acuático Córdoba", "type": "video", "yt_id": "Q_LtiMrmNso", "desc": "Toboganes y emocion en Andalucia."},
        {"name": "Mario Park - El parque acuático de Almería", "type": "video", "yt_id": "2ujn-Nw8O_c", "desc": "Aventura familiar en Mario Park."},
        {"name": "Aquapark Costa Teguise 2025 - Lanzarote", "type": "video", "yt_id": "6lHcyrexsX0", "desc": "Recorrido 4K por el parque canario."},
        {"name": "Aqualand El Arenal Mallorca POV", "type": "video", "yt_id": "iV6ijvlaovo", "desc": "Todos los toboganes en POV."},
        {"name": "Bahía Park Algeciras 2024 - Cádiz", "type": "video", "yt_id": "2iWyTSGNs18", "desc": "Diversion asegurada en Bahia Park Algeciras."},
        {"name": "Aquopolis Sevilla (Guadalpark) 2024", "type": "video", "yt_id": "HL223Z3tuk8", "desc": "Tour completo por Guadalpark en Sevilla."},
        {"name": "Aqua Natura Benidorm - Todos los toboganes", "type": "video", "yt_id": "wfJylCU7FJs", "desc": "Atracciones acuaticas de Terra Natura."},
        {"name": "Lago Taurito Water Park - Gran Canaria", "type": "video", "yt_id": "qjQgESobohY", "desc": "Parque acuatico unico en Mogan, Gran Canaria."},
        {"name": "Marineland Cataluña (Palafolls)", "type": "video", "yt_id": "UqTokyJ4rsU", "desc": "Parque acuatico familiar en Barcelona/Girona."},
        {"name": "Aquopolis Villanueva de la Cañada - Madrid", "type": "video", "yt_id": "6S7CFxdKjRc", "desc": "El mejor aquopolis de españa con todas las atracciones."},
        {"name": "Aqualand Torremolinos - Málaga", "type": "video", "yt_id": "-7wMpt4Vx_c", "desc": "Parque acuatico de Torremolinos con nuevos toboganes."},
        {"name": "Aqualand Bahía de Cádiz", "type": "video", "yt_id": "Y8wxdTZQa4o", "desc": "Diversion acuática en El Puerto de Santa María."},
        {"name": "Aquopolis Cartaya - Huelva", "type": "video", "yt_id": "NACFycIhBGc", "desc": "Guia del parque acuatico onubense."},
        {"name": "AquaCenter Menorca", "type": "video", "yt_id": "IYuXKTE5SS0", "desc": "Parque acuatico balear en Menorca."},
        {"name": "Aqualand Maspalomas - Gran Canaria", "type": "video", "yt_id": "dObSZkmnvMQ", "desc": "Todos los toboganes en Maspalomas."},
    ],
    "Agua: Playas y Calas": [
        {"name": "Las 10 mejores Playas de España 2025", "type": "video", "yt_id": "AkjcrQ-yP4k", "desc": "Explora las playas mas bonitas del litoral español."},
        {"name": "Las 5 mejores calas y playas de Mallorca (2025)", "type": "video", "yt_id": "yUvwY0kK_Z0", "desc": "Paraisos cristalinos en Mallorca."},
        {"name": "Formentera: Guía del destino más deseado 4K", "type": "video", "yt_id": "Pasd-nD24Qs", "desc": "Guia de viaje por Formentera."},
        {"name": "Las 5 mejores calas de la Costa Brava (2025)", "type": "video", "yt_id": "v_SKovw-_Vk", "desc": "Descubre el encanto de la Costa Brava."},
        {"name": "Costa Brava: Guía de viaje 7 días 2026 (4K)", "type": "video", "yt_id": "4lK3joHFJaE", "desc": "Plan perfecto para recorrer la Costa Brava."},
        {"name": "Las 5 mejores playas de Asturias (2025)", "type": "video", "yt_id": "mmwISRni7m4", "desc": "Descubre la belleza del litoral asturiano."},
        {"name": "Top 15 mejores playas de Cantabria", "type": "video", "yt_id": "8vLON75R6M0", "desc": "Calas y zonas de baño destacadas en Cantabria."},
        {"name": "Top 10 mejores playas de Murcia", "type": "video", "yt_id": "5JYndCeRTGA", "desc": "Las playas mas bonitas incluyendo Cabo de Palos."},
        {"name": "Las mejores playas del País Vasco", "type": "video", "yt_id": "b2fo9GJZT2M", "desc": "Recorrido por las impresionantes playas vascas."},
        {"name": "Fuerteventura: Las mejores playas del mundo", "type": "video", "yt_id": "N2F7tG5RM9M", "desc": "Top playas espectaculares de Canarias."},
        {"name": "Las 5 mejores playas de Cádiz (2025)", "type": "video", "yt_id": "2O4xGgQ1odY", "desc": "Los paraisos de la costa gaditana."},
        {"name": "Top 15 mejores playas de Huelva", "type": "video", "yt_id": "rE3YXm6kfxg", "desc": "Arena fina y blanca para toda la familia."},
        {"name": "Las 3 Mejores Playas en Galicia", "type": "video", "yt_id": "5OMMP28J9Fs", "desc": "Joyas de las Rias Baixas y costa gallega."},
        {"name": "Las 5 mejores calas y playas de Ibiza (2025)", "type": "video", "yt_id": "eF0ZFVIFWRo", "desc": "Descanso y fiesta en las mejores aguas."},
        {"name": "Menorca: Las Top 5 Playas Cristalinas", "type": "video", "yt_id": "XjTY4pssi1U", "desc": "Imprescindibles de la isla balear."},
        {"name": "Las 5 mejores playas de Lanzarote (2025)", "type": "video", "yt_id": "kxgG-n82IBI", "desc": "Playas unicas y volcanicas."},
        {"name": "Gran Canaria: Ruta por las 10 mejores playas", "type": "video", "yt_id": "VliSTNQa4SA", "desc": "Gran guia canaria."},
        {"name": "Las 5 mejores calas y playas de Alicante (2025)", "type": "video", "yt_id": "d8rtO3HcdB0", "desc": "Paraisos escondidos de la Costa Blanca."},
        {"name": "Top 15 mejores playas y calas de Almería", "type": "video", "yt_id": "2eEWEUFLYMM", "desc": "Costa de Almeria y Cabo de Gata."},
        {"name": "Las 5 mejores playas de Granada en 2025", "type": "video", "yt_id": "Jg6UTrNggJU", "desc": "Joyas de la Costa Tropical."},
        {"name": "Las 15 Mejores Calas y Playas de Tarragona", "type": "video", "yt_id": "5wVkADc2Fw8", "desc": "Guia de la Costa Dorada en 3 dias."},
        {"name": "Las 5 mejores calas y playas de Castellón (2025)", "type": "video", "yt_id": "sWP9zPpta3U", "desc": "Rincones de la Costa del Azahar."},
        {"name": "Top 15 mejores playas de A Coruña", "type": "video", "yt_id": "tnY7JLzvikE", "desc": "Playas espectaculares de Galicia del norte."},
        {"name": "Playa de las Catedrales - Lugo", "type": "video", "yt_id": "rinO_Ssu9bc", "desc": "Monumento natural en la mariña lucense."},
        {"name": "Las Mejores Playas cerca de Barcelona", "type": "video", "yt_id": "sp4F5CLnQ3E", "desc": "Escapadas a calas de la provincia de Barcelona."},
        {"name": "Las 5 Mejores Playas de Málaga", "type": "video", "yt_id": "M-H0BNF1oSE", "desc": "La Costa del Sol en su maximo esplendor."},
        {"name": "Top 10 mejores playas de Pontevedra", "type": "video", "yt_id": "TuQgJFwpMiA", "desc": "Zonas de baño imprescindibles en Rias Baixas sur."},
        {"name": "Playas de Guipúzcoa y País Vasco", "type": "video", "yt_id": "N4XZ5dYrLy0", "desc": "Lugares impresionantes del norte de españa."},
        {"name": "Playas y Calas de El Hierro", "type": "video", "yt_id": "T43cWcNto_Q", "desc": "Turismo en las Islas Canarias occidentales."},
        {"name": "Playas y Calas de La Gomera", "type": "video", "yt_id": "CDLsyoVb0r8", "desc": "Turismo en las Islas Canarias occidentales."},
    ],
    "Agua: Deportes Acuáticos": [
        {"name": "Surfeando Mundaka en pleno verano", "type": "video", "yt_id": "TkNS0NahHds", "desc": "Surf en una de las mejores olas de España."},
        {"name": "Olas de 4M en El Fronton - POV RAW", "type": "video", "yt_id": "nNg-DdqUxFc", "desc": "Bodyboard extremo en Canarias."},
        {"name": "Flyboard: Salimos volando con la moto de agua", "type": "video", "yt_id": "kcEB5_uIgIQ", "desc": "Experiencia extrema con flyboard."},
        {"name": "Snorkel en Cabo de Gata - Almería", "type": "video", "yt_id": "8nEbpGGTmUw", "desc": "Buceo en aguas cristalinas de Almeria."},
    ],
    "Agua: Piscinas Naturales": [
        {"name": "Las 10 mejores piscinas naturales de España", "type": "video", "yt_id": "dXek56url-A", "desc": "Pozas y charcos naturales imprescindibles."},
        {"name": "Piscinas naturales de Letur - Castilla-La Mancha", "type": "video", "yt_id": "loc8RYA_Xag", "desc": "Refrescate en el encanto de Letur."},
        {"name": "Top 15 Playas y Piscinas Naturales de Alicante", "type": "video", "yt_id": "TynumUKlWwI", "desc": "Zonas de baño unicas en Alicante."},
        {"name": "Top 15 Playas y Piscinas Naturales de Badajoz", "type": "video", "yt_id": "mr8-TJRgMg0", "desc": "Zonas de baño de interior en Extremadura."},
    ],
    "Diversión: Parques de Atracciones": [
        {"name": "PortAventura World - ATRACCIONES Y NOVEDADES", "type": "video", "yt_id": "RfDjBnqA_DU", "desc": "El Top 10 de atracciones en PortAventura."},
        {"name": "Parque Warner Madrid - Todas sus atracciones", "type": "video", "yt_id": "4IF9TIkqxg8", "desc": "El mejor dia en Parque Warner, montanas rusas y mas."},
        {"name": "Terra Mítica Benidorm", "type": "video", "yt_id": "SvqCqnXkGWs", "desc": "Guia de Terra Mitica en la Costa Blanca."},
        {"name": "Isla Mágica Sevilla en 4K", "type": "video", "yt_id": "qBmAM-yeNik", "desc": "Recorrido por el parque de atracciones sevillano."},
        {"name": "Tibidabo Barcelona - Todas las atracciones", "type": "video", "yt_id": "wVafyQFJyI0", "desc": "El parque mas antiguo en lo alto de Barcelona."},
        {"name": "Puy du Fou España - Toledo", "type": "video", "yt_id": "hfLWyYBHXzw", "desc": "Parque historico e inmersivo en Toledo."},
        {"name": "Dinópolis Teruel", "type": "video", "yt_id": "0qpgB7pZgAA", "desc": "Lugar magico entre dinosaurios en Aragon."},
        {"name": "Sendaviva Navarra - Parque y Animales", "type": "video", "yt_id": "Ycixgpw8oqA", "desc": "Aventura y naturaleza en Navarra."},
    ],
    "Agua: Ríos y Cascadas": [
        {"name": "Descenso del Sella con Amigos 2025", "type": "video", "yt_id": "mMF3IjiuBU8", "desc": "La fiesta de las piraguas en Asturias."},
        {"name": "Barranquismo Sierra de Guara - Huesca", "type": "video", "yt_id": "11E6BlwkmvY", "desc": "Descenso de cañones divertidos en Aragon."},
        {"name": "Nacimiento del Río Mundo - Albacete", "type": "video", "yt_id": "f6Zyt9-7reg", "desc": "El fenomeno natural del Reventon de los Chorros."},
        {"name": "Cañones del Sil en Barco - Galicia", "type": "video", "yt_id": "12gx78y-2C8", "desc": "Navegacion espectacular por la Ribeira Sacra."},
    ],
    "Diversión: Festivales de Verano": [
        {"name": "Arenal Sound Official Aftermovie", "type": "video", "yt_id": "OU3QgGAEUFM", "desc": "Locura y musica en la playa de Burriana."},
        {"name": "Mad Cool Official Aftermovie", "type": "video", "yt_id": "CuvMVb02NnM", "desc": "Resumen del macrofestival madrileno."},
        {"name": "Viña Rock Official Aftermovie", "type": "video", "yt_id": "alUOUJsaJWI", "desc": "Arte nativo y buen rollo en Villarrobledo."},
        {"name": "Primavera Sound Barcelona Aftermovie", "type": "video", "yt_id": "xb-D6MUPpFA", "desc": "La magia del festival mas indie del verano."},
    ],
    "Verano: Camping y Camper": [
        {"name": "Sangulí Salou - El Mejor Camping Resort", "type": "video", "yt_id": "cwjwMunIdmo", "desc": "Piscinas tematizadas y vida de resort en Tarragona."},
        {"name": "La Marina Resort Alicante", "type": "video", "yt_id": "BlUeJF53qSA", "desc": "Paraiso campista en la Costa Blanca."},
        {"name": "Ruta Camper por la Costa da Morte", "type": "video", "yt_id": "6kmpZBW0y0U", "desc": "Roadtrip por el litoral atlantico de Galicia."},
        {"name": "Vlog: ¿Cómo acampar por primera vez?", "type": "video", "yt_id": "R-O8GF_EPxQ", "desc": "Guia de iniciacion al vivac y la acampada natural."},
    ],
}

# --- Cocina Española (YouTube) ---
COCINA_ESPANOLA_YT = {
    "Paella Valenciana": [
        {"name": "PAELLA VALENCIANA receta tradicional", "type": "video", "yt_id": "1MzMde4FzBM", "desc": "Receta tradicional de paella valenciana.\n124K visitas"},
        {"name": "Como Aprendi a Hacer PAELLAS", "type": "video", "yt_id": "SyCZQM3PjCE", "desc": "Aprende a hacer paellas con esta guia.\n955K visitas"},
        {"name": "Paella Valenciana con todos sus TRUCOS", "type": "video", "yt_id": "vWySIREExjo", "desc": "La receta mas popular con todos sus trucos.\n1.0M visitas"},
        {"name": "PAELLA VALENCIANA TRADICIONAL PASO A PASO", "type": "video", "yt_id": "6YK4DLewG-8", "desc": "Trucos para que salga perfecta.\n313K visitas"},
        {"name": "Receta de PAELLA VALENCIANA AUTENTICA", "type": "video", "yt_id": "rKwoKpSRdNQ", "desc": "Paso a paso con todos los trucos.\n26K visitas"},
        {"name": "LA AUTENTICA PAELLA VALENCIANA!! Receta paso a paso", "type": "video", "yt_id": "Rh51jFzvADo", "desc": "La genuina paella valenciana, rechaza imitaciones.\n13K visitas"},
        {"name": "Paella Valenciana en pasos breves", "type": "video", "yt_id": "5THBRDiXu94", "desc": "Version rapida con lo esencial.\n20K visitas"},
        {"name": "Paella Valenciana - Pep Romany (Pont Sec)", "type": "video", "yt_id": "aU6Lm86i-T8", "desc": "Todos los detalles para la paella perfecta.\n23K visitas"},
        {"name": "Paella Valenciana a fuego de lena", "type": "video", "yt_id": "ABxiVd23hT4", "desc": "Paella tradicional cocinada a lena.\n1.1M visitas"},
        {"name": "Receta Paella Valenciana - Loli Dominguez", "type": "video", "yt_id": "1QpvPXWSu90", "desc": "La autentica receta de Valencia.\n1.9M visitas"},
        {"name": "Paella valenciana - Karlos Arguinano", "type": "video", "yt_id": "T-ppvkQdTu4", "desc": "Karlos Arguinano prepara su paella valenciana.\n323K visitas"},
        {"name": "Receta paella valenciana autentica - Amadeo Faus", "type": "video", "yt_id": "zrSyyNugKYo", "desc": "Receta como la hacian nuestros abuelos.\n4.9M visitas"},
        {"name": "How to Make Authentic Spanish Paella", "type": "video", "yt_id": "08W7LZDtnEI", "desc": "Traditional Spanish paella step by step (English).\n384K visitas"},
        {"name": "Paella Valenciana Grande para 50 personas", "type": "video", "yt_id": "zeigZDOEHgo", "desc": "Paella gigante para 50 personas.\n247K visitas"},
        {"name": "Paella Valenciana: Spain's Most Famous Dish - DW Food", "type": "video", "yt_id": "dy1o7xZjjbY", "desc": "Los secretos del plato mas famoso de Espana.\n1.5M visitas"},
        {"name": "Paella valenciana paso a paso - Receta ganadora", "type": "video", "yt_id": "7XT_MKHWcaY", "desc": "Paella de pollo y conejo, receta ganadora.\n705K visitas"},
        {"name": "Receta de la autentica paella valenciana (DOBLAJE)", "type": "video", "yt_id": "gGUfVX9iHyg", "desc": "La verdadera receta con doblaje comico.\n2.6M visitas"},
        {"name": "Como hacer una paella valenciana - Toni Montoliu", "type": "video", "yt_id": "fLWu0mTcdw0", "desc": "Paella a lena de forma tradicional.\n2.1M visitas"},
        {"name": "EL COMIDISTA - Haz paella como un valenciano", "type": "video", "yt_id": "f3PclRD44x4", "desc": "Aprende a cocinar paella sin que te digan arroz con cosas.\n489K visitas"},
        {"name": "LA AUTENTICA Paella Valenciana - Receta Tradicional", "type": "video", "yt_id": "TK_amAp3Vhk", "desc": "Receta tradicional paso a paso.\n96K visitas"},
        {"name": "PAELLA VALENCIANA - El truco de un buen sofrito", "type": "video", "yt_id": "hsmbneBN8uI", "desc": "Desde la Albufera, el truco del sofrito perfecto.\n245K visitas"},
        {"name": "Paella Valenciana (variantes por zona)", "type": "video", "yt_id": "5kQoyeXCxsI", "desc": "Variantes dependiendo de la zona.\n166K visitas"},
        {"name": "Paella Valencia (receta clasica)", "type": "video", "yt_id": "MAmDgDGL1XI", "desc": "La receta clasica de la paella.\n1.6M visitas"},
        {"name": "Las Medidas de la Paella para 3 a 10 personas", "type": "video", "yt_id": "5qiQtEY9GRM", "desc": "El tamano de la paella importa. Guia de medidas.\n739K visitas"},
        {"name": "PAELLA VALENCIANA para principiantes", "type": "video", "yt_id": "MdeDuXDNi54", "desc": "Todo explicado al detalle, tips y consejos.\n27K visitas"},
    ],
    "Tortilla de Patata": [
        {"name": "Tortilla de patatas - Receta de cocina espanola", "type": "video", "yt_id": "pvlkYYdIBV0", "desc": "La clasica tortilla de patatas espanola.\n12.2M visitas"},
        {"name": "Como hacer la tortilla de patatas perfecta", "type": "video", "yt_id": "THkedZNqAyU", "desc": "Trucos para la tortilla perfecta.\n1.3M visitas"},
        {"name": "La Tortilla De Patata De Un Chef Profesional", "type": "video", "yt_id": "epbWlp2FyxM", "desc": "Receta de un chef profesional.\n788K visitas"},
        {"name": "Tortilla de Patatas SUPER JUGOSA (Con Cebolla)", "type": "video", "yt_id": "YMmFrFdO7RM", "desc": "Receta paso a paso, super jugosa.\n219K visitas"},
        {"name": "Tortilla de Patatas Espanola", "type": "video", "yt_id": "uc8Pwe7alJ8", "desc": "Autentica tortilla de patatas con cebolla.\n674K visitas"},
        {"name": "Tortilla en restaurante 2 estrellas Michelin", "type": "video", "yt_id": "tqs579oIDwE", "desc": "Tortilla en un restaurante 2 estrellas Michelin.\n777K visitas"},
        {"name": "Tortilla de patatas: 8 errores - EL COMIDISTA", "type": "video", "yt_id": "rk0GhiJi5cQ", "desc": "Errores comunes y una receta que funciona.\n154K visitas"},
        {"name": "Tortilla Espanola - Menudos Torres", "type": "video", "yt_id": "lgyfCk9nx9I", "desc": "Tortilla espanola por los hermanos Torres.\n105K visitas"},
        {"name": "La mejor tortilla de patatas - Torres | RTVE Cocina", "type": "video", "yt_id": "QMfSJsA5OuM", "desc": "La mejor tortilla de patatas por los Torres.\n207K visitas"},
    ],
    "Gazpacho Andaluz": [
        {"name": "GAZPACHO andaluz facil, rapido y riquisimo", "type": "video", "yt_id": "8JIn8zydtNM", "desc": "Receta facil y rapida de gazpacho andaluz.\n1.7M visitas"},
        {"name": "El mejor GAZPACHO ANDALUZ en solo 5 minutos", "type": "video", "yt_id": "_FeCqwWd7rA", "desc": "Gazpacho andaluz en 5 minutos.\n21K visitas"},
        {"name": "GAZPACHO ANDALUZ casero (Sin pan) - La mejor receta del verano", "type": "video", "yt_id": "AgMlwUpP-h4", "desc": "Gazpacho casero sin pan, receta veraniega.\n21K visitas"},
        {"name": "GAZPACHO ANDALUZ tradicional y super facil", "type": "video", "yt_id": "OcMbTw795r0", "desc": "Receta tradicional y super facil.\n8K visitas"},
    ],
    "Churros con Chocolate": [
        {"name": "Receta: Churros con chocolate", "type": "video", "yt_id": "ead6rC2h2iA", "desc": "Churros con chocolate clasicos.\n5K visitas"},
        {"name": "Como hacer Chocolate para Churros (Receta facil)", "type": "video", "yt_id": "qUV0X43Gat0", "desc": "Receta facil y rapida de chocolate para churros.\n151K visitas"},
        {"name": "Receta: churros con chocolate - Cometelo", "type": "video", "yt_id": "G_2pHRodYkY", "desc": "Churros con chocolate de Canal Sur.\n107K visitas"},
        {"name": "Como hacer CHURROS en casa", "type": "video", "yt_id": "JzErv3dAlTk", "desc": "Churros caseros faciles, tambien llamados porras.\n3K visitas"},
        {"name": "CHURROS CASEROS - Sabores de abuelas", "type": "video", "yt_id": "u7l3NwAim58", "desc": "Las recetas son recuerdos y emociones.\n378K visitas"},
        {"name": "Churros con chocolate - Torres en la Cocina | RTVE", "type": "video", "yt_id": "MJ5ShL2mG3g", "desc": "Receta de los hermanos Torres para RTVE.\n43K visitas"},
        {"name": "Como Hacer Churros desde Espana", "type": "video", "yt_id": "jFlthH-1Wy8", "desc": "Churros autenticos directamente desde Madrid.\n877K visitas"},
        {"name": "Cometelo | Chocolate y churros", "type": "video", "yt_id": "v4jIRjojh9A", "desc": "Receta de Enrique Sanchez en Canal Sur.\n311K visitas"},
    ],
    "Fabada Asturiana": [
        {"name": "Fabada Asturiana - Receta Tradicional Autentica", "type": "video", "yt_id": "NvhuoE8ENGQ", "desc": "Receta tradicional autentica de fabada.\n615K visitas"},
        {"name": "FABADA ASTURIANA Tradicional - Muy Facil de Hacer", "type": "video", "yt_id": "fhIrWSrW6oo", "desc": "Se hace practicamente sola.\n344K visitas"},
        {"name": "Fabada asturiana - Jose Andres | RTVE Cocina", "type": "video", "yt_id": "t7M40DX-ZA8", "desc": "Jose Andres con Pedro y Marcos Moran.\n98K visitas"},
        {"name": "FABADA ASTURIANA, la receta clasica que sale SIEMPRE BIEN", "type": "video", "yt_id": "kVa4irjFZd4", "desc": "Receta clasica de Directo al Paladar.\n191K visitas"},
        {"name": "ROBINFOOD - Fabada asturiana + Arroz con leche", "type": "video", "yt_id": "9LaIKAoHIZs", "desc": "David de Jorge con fabada y arroz con leche.\n623K visitas"},
        {"name": "Receta de Fabada Asturiana - La Mejor Fabada del Mundo", "type": "video", "yt_id": "LUXM-keti8M", "desc": "Ganadora del concurso La Mejor Fabada 2011.\n55K visitas"},
        {"name": "Cachopo y Fabada en un Famoso Restaurante Asturiano", "type": "video", "yt_id": "8fHQc6KMVaQ", "desc": "Cachopo y fabada en restaurante asturiano.\n201K visitas"},
        {"name": "Fabada Asturiana o fabes - Receta tradicional muy facil", "type": "video", "yt_id": "oXcqidGXxrs", "desc": "Con chorizo, morcilla, panceta y lacon.\n169K visitas"},
        {"name": "FABADA ASTURIANA hecha por un asturiano - TODOS los TRUCOS", "type": "video", "yt_id": "U6-DlyxeXto", "desc": "Todos los trucos de un asturiano con 2 estrellas Michelin.\n1.5M visitas"},
        {"name": "Fabada Asturiana en olla rapida", "type": "video", "yt_id": "xMNbr83Iog4", "desc": "Menos de la mitad de tiempo y todo sabor.\n151K visitas"},
        {"name": "FABADA ASTURIANA (Receta Historica)", "type": "video", "yt_id": "lcFUCaqAjCo", "desc": "Fabes cremosas cocidas lentamente.\n1.1M visitas"},
        {"name": "Fabada asturiana de Casa Gerardo - receta con estrella", "type": "video", "yt_id": "ibBQBEMT2k0", "desc": "Receta de Casa Gerardo, 1 estrella Michelin.\n830K visitas"},
        {"name": "Receta de fabada con chorizo y morcilla - Karlos Arguinano", "type": "video", "yt_id": "z4rjqgSsqzI", "desc": "Karlos Arguinano en homenaje a Fernando Alonso.\n171K visitas"},
        {"name": "Fabada ASTURIANA - Cocina tradicional", "type": "video", "yt_id": "dVySV8z7RrM", "desc": "Mi mejor receta de fabada en olla tradicional.\n17K visitas"},
        {"name": "Una fabada asturiana muy premiada - RTVE Cocina", "type": "video", "yt_id": "d5gbF6x_Kyk", "desc": "Fabada repleta de sabor, tradicion y amor.\n22K visitas"},
    ],
    "Cocido Madrileno": [
        {"name": "Cocido madrileno - el guiso mas facil y rico del mundo", "type": "video", "yt_id": "mAHJWcYONsQ", "desc": "Receta tradicional muy facil.\n1.9M visitas"},
        {"name": "Receta de cocido madrileno - Karlos Arguinano", "type": "video", "yt_id": "HSY6RJNNp7A", "desc": "Cocido tradicional con garbanzos y carne.\n376K visitas"},
        {"name": "Cocido madrileno - Jose Andres | RTVE Cocina", "type": "video", "yt_id": "HAXfsSoXZGs", "desc": "Jose Andres con El Negri.\n108K visitas"},
        {"name": "Cocido Madrileno Tradicional - La Mejor Receta", "type": "video", "yt_id": "uad6ABaQy3w", "desc": "Receta de madres y abuelas de toda la vida.\n66K visitas"},
    ],
    "Patatas Bravas": [
        {"name": "Patatas BRAVAS caseras con su salsa", "type": "video", "yt_id": "Qph_wEWWTFY", "desc": "Receta casera facil con salsa brava.\n1.7M visitas"},
        {"name": "Cometelo | Patatas Bravas", "type": "video", "yt_id": "NDuxKkjxpqA", "desc": "Patatas bravas de Enrique Sanchez.\n281K visitas"},
        {"name": "EL COMIDISTA - Las bravas favoritas del hombre que ha probado 900", "type": "video", "yt_id": "3PY7QrBr5No", "desc": "Un cazador de bravas elige las mejores.\n615K visitas"},
        {"name": "Patatas bravas - El TRUCO de la salsa y las patatas", "type": "video", "yt_id": "qEsy45dW0gU", "desc": "Tan importante es la salsa como el truco de las patatas.\n706K visitas"},
        {"name": "Las patatas bravas de Alberto Chicote", "type": "video", "yt_id": "WSBl5j-3tZ0", "desc": "Salsa brava al estilo de Madrid.\n298K visitas"},
        {"name": "Las patatas bravas de Jordi Cruz - Una salsa de escandalo", "type": "video", "yt_id": "zFPq7YjMURk", "desc": "Receta del restaurante Ten's de Barcelona.\n865K visitas"},
        {"name": "Las patatas bravas mas famosas de Madrid - salsa secreta", "type": "video", "yt_id": "5lA5PwjHMjY", "desc": "Las legendarias bravas del bar Docamar.\n263K visitas"},
    ],
    "Croquetas": [
        {"name": "Croquetas de Jamon - Receta Tradicional Casera", "type": "video", "yt_id": "ktv5vseGTSY", "desc": "Receta tradicional muy facil y casera.\n824K visitas"},
        {"name": "Croquetas de jamon - Las mejores que he probado", "type": "video", "yt_id": "XqEzs3piruc", "desc": "Las mejores croquetas de jamon.\n311K visitas"},
        {"name": "Hago 8 croquetas espanolas", "type": "video", "yt_id": "n_gN18C-fVY", "desc": "8 variedades de croquetas espanolas.\n159K visitas"},
        {"name": "Croquetas caseras de jamon y pollo", "type": "video", "yt_id": "Bv3bPIJw8mc", "desc": "Receta casera de jamon y pollo.\n90K visitas"},
        {"name": "Croquetas de jamon iberico - sabor mediterraneo", "type": "video", "yt_id": "jpEOkpxpp-w", "desc": "Croquetas con sabor mediterraneo.\n610K visitas"},
        {"name": "Croquetas de bacalao - receta espanola", "type": "video", "yt_id": "zulOHBy1QQc", "desc": "Clasicas croquetas de bacalao.\n161K visitas"},
        {"name": "Las mejores croquetas de Espana - Lo comprobamos", "type": "video", "yt_id": "3Wxy0js-O18", "desc": "Buscando las mejores croquetas de Espana.\n380K visitas"},
        {"name": "Las mejores croquetas del mundo - RTVE Cocina", "type": "video", "yt_id": "Zrr4gXOMlHs", "desc": "Espana Directo busca las mejores.\n408K visitas"},
        {"name": "Croquetas de cocido madrileno", "type": "video", "yt_id": "c61sexW6mws", "desc": "Aprovechando el cocido para hacer croquetas.\n195K visitas"},
        {"name": "Como hacer las croquetas de jamon - TODOS me piden la receta", "type": "video", "yt_id": "BMBSuUDnGPU", "desc": "La receta que todo el mundo te pide.\n2.2M visitas"},
        {"name": "Cometelo | Croquetas de puchero", "type": "video", "yt_id": "lXQpxsk3uVM", "desc": "Croquetas de puchero de Enrique Sanchez.\n908K visitas"},
        {"name": "Croquetas de pollo - La receta secreta de mi abuela", "type": "video", "yt_id": "QK9X-j3dysg", "desc": "La receta secreta de la abuela.\n2.7M visitas"},
    ],
    "Pulpo a la Gallega": [
        {"name": "Pulpo a la Gallega - Receta paso a paso", "type": "video", "yt_id": "oWjmKhA6NE0", "desc": "Polbo a Feira explicado paso a paso.\n1.4M visitas"},
        {"name": "Pulpo a la gallega, asi de facil", "type": "video", "yt_id": "rAbeLpMWhpI", "desc": "Receta muy facil en casa.\n438K visitas"},
        {"name": "Receta de pulpo a la gallega - Karlos Arguinano", "type": "video", "yt_id": "LpuX3UwIMz8", "desc": "Con patatas cocidas y pimenton.\n184K visitas"},
        {"name": "Como Cocer Pulpo al punto y receta a la gallega", "type": "video", "yt_id": "gmd4KveWOf8", "desc": "El gran truco para que quede perfecto.\n125K visitas"},
        {"name": "Como hacer pulpo a la gallega paso a paso", "type": "video", "yt_id": "uSTcX5CnuWE", "desc": "Receta paso a paso completa.\n555K visitas"},
        {"name": "PULPO A LA GALLEGA o PULPO A FEIRA - Receta tradicional", "type": "video", "yt_id": "AuCLjqD_7hg", "desc": "Receta tradicional facil y rapida.\n45K visitas"},
        {"name": "Pulpo a feira - Jose Andres | RTVE Cocina", "type": "video", "yt_id": "zdhciodxI_0", "desc": "Jose Andres con Tonino.\n21K visitas"},
    ],
    "Pisto Manchego": [
        {"name": "PISTO MANCHEGO", "type": "video", "yt_id": "g31e0xQTADo", "desc": "Clasico de la gastronomia espanola. Facil, rapido y economico.\n35K visitas"},
    ],
    "Calamares a la Romana": [
        {"name": "Calamares a la romana - Los TRUCOS del REBOZADO PERFECTO", "type": "video", "yt_id": "FJS71Q5R2Ps", "desc": "Los trucos del rebozado perfecto.\n1.7M visitas"},
    ],
    "Salmorejo Cordobes": [
        {"name": "Salmorejo Cordobes - Autentica Receta muy Facil", "type": "video", "yt_id": "FuJk_J9dSj8", "desc": "Sopa fria andaluza autentica.\n598K visitas"},
    ],
    "Empanada Gallega": [
        {"name": "Empanada gallega de atun con masa casera", "type": "video", "yt_id": "ftRtUXnaENU", "desc": "Receta antigua convertida en manjar.\n2.8M visitas"},
    ],
    "Bacalao al Pil Pil": [
        {"name": "BACALAO AL PIL PIL - Receta Facil y Salsa Perfecta", "type": "video", "yt_id": "b2khuUYhajM", "desc": "Maravilla tradicional de la cocina vasca.\n97K visitas"},
    ],
    "Pimientos de Padron": [
        {"name": "PIMIENTOS DE PADRON - Receta facil en 7 minutos", "type": "video", "yt_id": "-cPcVXcvT_M", "desc": "Unos pican y otros no. Receta en 7 minutos.\n746 visitas"},
    ],
    "Crema Catalana": [
        {"name": "Crema Catalana - Receta Tradicional Facil y Rapida", "type": "video", "yt_id": "frJfPGTAHyE", "desc": "Receta tradicional facil, rapida y deliciosa.\n150K visitas"},
    ],
    "Cochinillo Asado": [
        {"name": "COCHINILLO asado AL HORNO: CRUJIENTE y TIERNO", "type": "video", "yt_id": "VNhuuYouySk", "desc": "Crujiente por fuera, tierno por dentro. Facil y funciona.\n113K visitas"},
    ],
    "Papas Arrugadas con Mojo Picon": [
        {"name": "Papas arrugadas con mojo picon - receta canaria", "type": "video", "yt_id": "NTtJ3uXzvz4", "desc": "Receta tradicional de las Islas Canarias.\n88K visitas"},
    ],
    "Pintxos Vascos": [
        {"name": "2 Pinchos Vascos para fiestas faciles y rapido", "type": "video", "yt_id": "zOibNoXttFU", "desc": "Aperitivos faciles y rapidos.\n8K visitas"},
    ],
    "Gambas al Ajillo": [
        {"name": "Gambas al ajillo: la receta de mi madre", "type": "video", "yt_id": "2tZlO8vNMtk", "desc": "Clasico de las tapas espanolas.\n257K visitas"},
    ],
    "Callos a la Madrilena": [
        {"name": "Callos a la madrilena - el aperitivo mas famoso de Madrid", "type": "video", "yt_id": "jdN4zXuUU6Q", "desc": "El aperitivo mas famoso de los bares de Madrid.\n243K visitas"},
    ],
    "Patatas a la Riojana": [
        {"name": "La receta de las autenticas PATATAS A LA RIOJANA", "type": "video", "yt_id": "e2_o8lfulGY", "desc": "Receta autentica riojana con chorizo.\n449K visitas"},
    ],
}


# --- Cámaras y Directos de España (M3U8 Nativo) ---
# Streams HLS públicos verificados. No se scrapea nada. El addon intenta ser lo mas legal posible.
WEBCAMS_ES = {
    "Explora España en Vivo": {
        "Playas y Costas": [
            {"name": "Playas de Cataluña (Multicámara HD)", "url": "https://directes-tv-int.3catdirectes.cat/live-content/beauties-hls/master.m3u8", "desc": "Cámaras en directo de playas y paisajes de Catalunya (TV3)."},
            {"name": "Playas de Cataluña (Alt)", "url": "https://directes-tv-cat.3catdirectes.cat/live-content/beauties-hls/master.m3u8", "desc": "Enlace alternativo de las cámaras del temps de 3Cat."},
            {"name": "Interalmería — Costa de Almería", "url": "https://interalmeria.tv/directo/live.m3u8", "desc": "Emisión directa con cobertura del levante almeriense."},
            {"name": "Vistas de la Costa Blanca", "url": "https://streaming005.gestec-video.com/hls/canal24.m3u8", "desc": "Panorámicas costeras y playas desde Alicante hasta Benidorm (8 La Marina)."},


            {"name": "Playa de las Canteras (Canarias)", "url": "https://hd-auth.skylinewebcams.com/live.m3u8?a=5doh1scq4mgmq80nu11bnf5kp3", "desc": "Cámara en directo desde Las Palmas (enlace rotativo, podría fallar)."},
            {"name": "Vistas de A Coruña", "url": "https://www.crtvg.es:1554/hls/coruna/index.m3u8", "desc": "Cámara fija en alta definición del entorno coruñés."},
            {"name": "Faro de Fisterra (Galicia)", "url": "https://www.crtvg.es:1554/hls/fisterra/index.m3u8", "desc": "El Fin del Mundo, vistas atlánticas."},
        ],
        "Ciudad y Puertos": [
            {"name": "Santiago (Praza do Obradoiro)", "url": "https://www.crtvg.es:1554/hls/obradoiro/index.m3u8", "desc": "Cámara 24h a los pies de la Catedral de Santiago."},
            {"name": "Vistas de Valencia — 7 Televalencia", "url": "https://play.cdn.enetres.net/9E9557EFCEBB43A89CEC8FBD3C500247022/028/playlist.m3u8", "desc": "Conexiones y programación autonómica con planos de Valencia."},
            {"name": "Vistas C. Valenciana — ROTV", "url": "https://rotv.romediavalencia.com:3839/live/rotvlive.m3u8", "desc": "Cadena regional valenciana."},
            {"name": "Granada Music & Vistas", "url": "https://cloudvideo.servers10.com:8081/8032/index.m3u8", "desc": "Emisión con vistas estáticas de Granada y banda sonora."},
            {"name": "Lebrija TV (Sevilla)", "url": "https://cloudvideo.servers10.com:8081/8094/index.m3u8", "desc": "Conexiones locales y vistas de la comarca sevillana."},
        ],
        "Montaña y Esquí": [
            {"name": "La Tierra desde la ISS (NASA)", "url": "https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8", "desc": "Cámara HD en directo montada en el exterior de la Estación Espacial Internacional."},
        ],
        "Naturaleza y Fauna": [
            {"name": "Televisión Consciente (Naturaleza)", "url": "https://cdn318.fractalmedia.es/318/live/hls/tvc/master.m3u8", "desc": "Canal 24h de documentales de naturaleza, paisajes y bienestar."},
            {"name": "Doñana Naturaleza (Huelva)", "url": "https://cloudvideo.servers10.com:8081/8050/index.m3u8", "desc": "Emisión paisajística desde el entorno del Parque Nacional de Doñana."},
        ],
    },
    "TV Regional en Directo": [
        {"name": "RTVE 24h (Nacional)", "yt_id": "UCfHptOfCGvKbHdFhfjJnWpA", "desc": "Canal 24 Horas de Radio Televisión Española en directo continuo."},
        {"name": "Telemadrid INT — Madrid", "yt_id": "UCwN-x4q24uH1e7d2V3oF-4g", "desc": "Emisión continua del canal internacional de Telemadrid."},
        {"name": "Canal Sur — Andalucía", "yt_id": "UCeS168L6t3c7n66nU_O144g", "desc": "Televisión pública de Andalucía: costumbres, actualidad y noticias."},
        {"name": "TVG — Galicia", "yt_id": "UC7dxTqnuQI6IxCZMmJG_MOw", "desc": "Televisión de Galicia en directo de forma ininterrumpida."},
        {"name": "Aragón TV", "url": "https://cartv.streaming.aranova.es/hls/live/aragontv_canal1.m3u8", "desc": "Canal internacional oficial de Aragón."},
        {"name": "Canal Extremadura", "url": "https://canalextremadura-live.flumotion.cloud/canalextremadura/live_all/playlist_dvr.m3u8", "desc": "Canal de Extremadura oficial en abierto."},

        {"name": "9 La Loma TV — Jaén", "url": "https://9laloma.tv/live.m3u8", "desc": "Televisión local de la comarca Loma de Úbeda (Jaén), en directo."},
        {"name": "Univers Faller — Valencia", "url": "https://cloud2.streaminglivehd.com:1936/universfaller/universfaller/playlist.m3u8", "desc": "Canal fallero valenciano en directo."},
        {"name": "TVReus — Tarragona", "url": "https://eu1.servers10.com:8081/8166/index.m3u8", "desc": "Televisión de Reus (Tarragona) en directo."},
        {"name": "Onda Valencia TV", "url": "https://cloudvideo.servers10.com:8081/8116/index.m3u8", "desc": "Televisión de la Comunitat Valenciana en directo."},
        {"name": "Onda 15 TV", "url": "https://cloudvideo.servers10.com:8081/8034/index.m3u8", "desc": "Televisión local en directo."},
        {"name": "TEF (Ibiza y Formentera)", "url": "https://eu1.servers10.com:8081/8172/index.m3u8", "desc": "Televisión de Eivissa y Formentera en directo."},
        {"name": "Galicia TV Europa", "url": "https://crtvg-europa.flumotion.cloud/playlist.m3u8", "desc": "Señal internacional de la Corporación Radio y Televisión de Galicia."},
        {"name": "Canal 33 — Madrid", "url": "https://media2.streambrothers.com:1936/8140/8140/playlist.m3u8", "desc": "Emisión en directo de Canal 33 Madrid."},
        {"name": "M95 Televisión Marbella", "url": "https://limited2.todostreaming.es/live/m95-livestream.m3u8", "desc": "Emisión en directo de M95 TV Costa del Sol."},
        {"name": "RTV Marbella", "url": "https://streaming.rtvmarbella.tv/hls/streamingweb.m3u8", "desc": "Radio Televisión Marbella en directo."},
        {"name": "Navarra Televisión", "url": "https://eu1.servers10.com:8081/8122/index.m3u8", "desc": "Televisión autonómica principal de la Comunidad Foral de Navarra."},

        {"name": "Canal 4 Mancha Centro", "url": "https://5924d3ad0efcf.streamlock.net/canal4/canal4live/playlist.m3u8", "desc": "Emisión local de Castilla-La Mancha."},

    ],

}